<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12">
         <div class="w-xxxx-4 m-l-xxxx-1">
             <h1><?php echo $title_form; ?></h1>
            <?php echo $adminForm->openTag(); ?>
            <?php echo $adminForm->getAllRow(); ?>
            <?php echo $adminForm->endTag(); ?>
       </div>
    </div>
</div>
<script>
$(document).ready(function(){
    $("#frmredireccion").validate();
});
</script>