<?php
define("ADMINISTRAR_SEO",                "administrar_seo");
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_SEO);
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_SEO);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_SEO);

define("ADMINISTRAR_REDIRECCIONES_301",      "administrar_redirecciones_301");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_REDIRECCIONES_301);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_REDIRECCIONES_301);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_REDIRECCIONES_301);
